### ISSUE TITLE
山东省json

### ISSUE THREAD

**Issue by huihuiteresa** [zhangyu9609/echarts-mapJson#1]
有没有济南莱芜合并后的json呀。

**Comment by zhangyu9609** [comment]
有的，我等会儿更新下，你关注下。
![莱芜](https://user-images.githubusercontent.com/32734769/79959500-cad39680-84b6-11ea-83ad-7f7b55ce96e2.png)

**Comment by zhangyu9609** [comment]
你要的是山东省的还是济南市的？
![山东省](https://user-images.githubusercontent.com/32734769/79960240-c196f980-84b7-11ea-8eee-a5ca9f9ccbc2.png)

**Comment by huihuiteresa** [comment]
我找到了，谢谢啦。  是山东省的json，现在好多莱芜还是地级市的。

不好意思没及时回复，  谢谢。

**Comment by zhangyu9609** [comment]
不用哈，有用就行，你的反馈也是对这个数据更新的帮助。
