### ISSUE TITLE
重庆市两江新区geojson

### ISSUE THREAD

**Issue by iaminvictus1993** [zhangyu9609/echarts-mapJson#3]
这个区不是传统得行政区域，是 江北 渝北 北碚 三个区 各取部分拼成得

**Comment by zhangyu9609** [comment]
各取部分怎么理解？0_0

**Comment by zhangyu9609** [comment]
> 这个区不是传统得行政区域，是 江北 渝北 北碚 三个区 各取部分拼成得

各取部分怎么理解？0_0

**Comment by zhangyu9609** [comment]
> 这个区不是传统得行政区域，是 江北 渝北 北碚 三个区 各取部分拼成得


[重庆市两江新区.zip](https://github.com/zhangyu9609/echarts-mapJson/files/5208060/default.zip)
看看这个符不符合你说的这个区。

**Comment by iaminvictus1993** [comment]
> > 这个区不是传统得行政区域，是 江北 渝北 北碚 三个区 各取部分拼成得
> 
> [重庆市两江新区.zip](https://github.com/zhangyu9609/echarts-mapJson/files/5208060/default.zip)
> 看看这个符不符合你说的这个区。

嗯，谢谢。就是这个

**Comment by zhangyu9609** [comment]
> > > 这个区不是传统得行政区域，是 江北 渝北 北碚 三个区 各取部分拼成得
> > 
> > 
> > [重庆市两江新区.zip](https://github.com/zhangyu9609/echarts-mapJson/files/5208060/default.zip)
> > 看看这个符不符合你说的这个区。
> 
> 嗯，谢谢。就是这个

ok
